### ISSUE TITLE
Inserting a numeral into a formatted field breaks formatting

### ISSUE THREAD

**Issue by wangjohn** [stripe/jquery.payment#108]
To reproduce the bug, go into a formatted field (like the credit card field or the expiration date field) and type some valid numbers. Then, insert a number into the middle of the numbers.

For example, let's say I was using the credit card field. I'll use the `|` operator to mark the position of the cursor. I might have filled half of it out like so:
```
1234 1234|
```

Then, If I add a number to the end of the first group of 4 numbers, this is what will happen:
```
12343 1234|
```

There are two things that are unintuitive:

1. The new number is not formatted as `1234 3123 4`.
2. The cursor moves back to the end of the input field, instead of like this: `1234 3|123 4`.

You can see this behavior in the example: http://stripe.github.io/jquery.payment/example/.

**Comment by jamesreggio** [comment]
So, I think I unintentionally fixed the first problem, where the new digit was being grouped with the first group instead of being pushed into the second group. The problem with the cursor moving to the end is ongoing, but I'm going to track it with the more concisely-worded issue #121.
