### ISSUE TITLE
Month validator Broken on android

### ISSUE THREAD

**Issue by wadewilliams** [stripe/jquery.payment#112]
Using samsung galaxy s5 with chrome, the month validator is impossible to get by. the / is not added and it is not possible to get to validate by entering the slash yourself.

**Comment by mtomov** [comment]
Hello,

We are experiencing the same issue with  Samsung Galaxy S5 Mini and a Galaxy S6. 

@wadewilliams have you found a workaround ?

Thanks!

**Comment by mtomov** [comment]
Actually, the fix is to follow the recommendations and use `type: tel`

https://github.com/stripe/jquery.payment#mobile-recommendations
