### ISSUE TITLE
Cursor jump when correcting

### ISSUE THREAD

**Issue by logsol** [stripe/jquery.payment#121]
If you already entered a number and click into the field to correct one digit, the cursor is moving to the end of the card number after you hit backspace. This affect should be avoided.

**Comment by jondavidjohn** [comment]
I have [forked this plugin](https://github.com/jondavidjohn/payform) to make it easier to consume via npm, node, and browserify without the jQuery dependency.  I have fixed this issue in that fork.

If you're interested in the fix, it was with [this commit](https://github.com/jondavidjohn/payform/commit/205042ec3da5d61352acc54de69ffce74943f4f6).  Specifically saving the cursor's position and resetting post-format.

**Comment by narkeeso** [comment]
I started with @jondavidjohn's fix but found when tabbing it would trigger the change event and cause the focus to go back to the previous input. Tested in all major browsers so far.
