### ISSUE TITLE
Add formatCardNumber function (versus only binding to an input field)

### ISSUE THREAD

**Issue by JamoCA** [stripe/jquery.payment#124]
I'm capturing credit card entries using hardware and populating the input field via javascript.  The updated value is not formatted and there doesn't seem to be any way to trigger an update.  The value is only validated and formatted if manually typed or pasted into the field.

    $('input.cc-num').payment('formatCardNumber');
    $('input.cc-num').val('4444333322221111');  /* this entry isn't formatted or validated */

I'd really like a function exposed to format any text string (if valid) as a credit card (optioanlly with spaces) without the requirement of it being bound to an input field.  (If the value is invalid, return NULL or an empty string.)  Is this possible?

My primary reason for asking is because data entry will be performed in a public place and I don't want to leave a validated credit card fully visible after it is entered and am masking all digits except the last 4.  Currently the format function can only be performed on a input field during manual entry.

**Comment by jamesreggio** [comment]
Apologies for the delay.

An undocumented method already exists for this purpose: `$.payment.formatCardNumber`. I don't expect its interface to change (since it's already been exposed publicly), so I'd say it's safe for you to use.

**Comment by JamoCA** [comment]
I tried the method and it works perfectly.  Thanks!

    $.payment.formatCardNumber('4444333322221111')

returns

    4444 3333 2222 1111

**Comment by jamesreggio** [comment]
Glad to hear it.
