### ISSUE TITLE
Android - '0' or '1' as first digit of expiry doesn't format correctly

### ISSUE THREAD

**Issue by markstreich** [stripe/jquery.payment#125]
Hi,

The changes made in the below commit do not account for '0' or '1' being the first digit entered in the expiration date input.

The input will format to `05 / ` when `5` is entered, but when `10`, `11` or `12` is entered, it doesn't add the slash separator.

https://github.com/stripe/jquery.payment/commit/273d79a08c82795eb24ec36463055e973abfe43c#diff-e8c62c763279e798ac80ce82ad65df8b

I won't attempt to write the coffeescript, but something like the following JS around line 560 seems to fix it.

```js
	if (mon.length === 2 && sep.length === 0) {
		sep = ' / ';
	}
```

Also, if you are using a 'tel' input type on android as we are, the following will help usability when backspace after month is entered:
```js
	if (sep.length !== 3) {
		sep = '';
	}
```

**Comment by keithchu** [comment]
+1 – can we get an update on this issue?
