### ISSUE TITLE
formatCardNumber clears credit card input fields Firefox Android.

### ISSUE THREAD

**Issue by jlangston** [stripe/jquery.payment#135]
Using jquery.payment's $(''#CreditCardNum").payment('formatCardNumber') method on the card input field has issues when using firefox on android version 4.4.2 and earlier. After entering the first 4 numbers upon entering the 5th the input field is cleared out when it attempts to format the input.

**Comment by jamesreggio** [comment]
Sorry about the delay, but I'm not able to reproduce this problem. Could you provide a precise Android OS + Firefox version to help me track this down?

**Comment by jamesreggio** [comment]
(I should note that everything appears to work correctly on Android 4.4.2 with the latest Firefox—35, at this time.)
