### ISSUE TITLE
Call jQuery `.()change` when modifying `.val()` on text fields

### ISSUE THREAD

**Issue by callumj** [stripe/jquery.payment#145]
When pasting (or autofilling via 1Password/etc) the values are correctly set on the specific form fields but `change` events are not being triggered when the reformats occur. This breaks integration with frameworks like Ember who use `change` to update the value of input bindings.

**Comment by jenanwise** [comment]
Hi there! Sorry for the very late reply.

The 'change' event is a tricky beast and not something that we want to manually trigger. Browsers don't agree on what it really means, and as far as I know it always only triggers after a commit-like action on an input field (blurring, submitting, etc), so we definitely don't want to trigger it synthetically on `.val()` updates. I'm not familiar with Ember and I'm not sure why it would only be listening for raw 'change' events.

I'm going to close this. If you are still having trouble, please feel free to re-open, but please provide a jsfiddle link to a minimal reproduction, as well as information about which browsers and operating systems are affected.
