### ISSUE TITLE
"fill_in" in Capybara/RSpec failing for some fields

### ISSUE THREAD

**Issue by keithchu** [stripe/jquery.payment#149]
I'm using `fill_in` to test CC fields governed by jquery.payment, and the fields don't appear to accept the complete input. The fields in question are the cardNumber and cardExpiry.

Using `fill_in` with "1234123412341234", for example, results in a cardNumber field filled with just "1234". I think that the formatter is trying to insert a space, which is for some reason causing the rest of the value not to be filled in.

**Comment by jamesreggio** [comment]
`jquery.payment` is built for human input, which happens one keystroke at a time. It's not amenable to testing systems unless they emulate this character-by-character input.

I don't know the specifics of Capybara/RSpec's automation, but try calling `fill_in` for each number individually and see if that solves your problem.

If not, let me know and I'll reopen this issue.

**Comment by keithchu** [comment]
@jamesreggio I just did a test and it looks like every character is registering as a separate keypress, so that doesn't seem to be the issue. Additionally, this has only popped up as a problem after https://github.com/stripe/jquery.payment/commit/3dc241e9188407042026c6d39ee74480504c3715 was merged. Manually reverting that change causes RSpec to function as expected with fill_in.

**Comment by jamesreggio** [comment]
Ah, I see the problem now. I'll reopen to track and try to get a fix out soon.

**Comment by jamesreggio** [comment]
That said, you may want to chance your test to use a semi-valid credit card, like `4242424242424242`. (This is a Visa card that passes the Luhn check.) We don't have any formatters for cards that begin with the `1234` pattern, so you wouldn't actually see any whitespace inserted.

**Comment by keithchu** [comment]
Thanks, @jamesreggio!

**Comment by wagner** [comment]
@keithchu you can try Capybara's `native.send_keys` instead of `fill_in`:

```ruby
'4242424242424242'.split('').each { |c| find_field('card_number').native.send_keys(c) }
```
I'm using Selenium and it works like a charm.

**Comment by keithchu** [comment]
That worked. Thanks!

**Comment by jamesreggio** [comment]
Thank you, @wagner!

**Comment by patrickgordon** [comment]
:+1: thanks for the solution @wagner. Works like a charm!

**Comment by iainbeeston** [comment]
This only seems to work in selenium... what about other solutions? (PhantomJS, SlimerJS?, CapybaraWebkit?)

**Comment by jjbananas** [comment]
I managed to get it to work with CapybaraWebkit by setting the value with a jQuery script executed on the page:

```ruby
def client_set_value(selector, value)
  script = "$('#{selector}').val('#{value}');"
  page.driver.browser.execute_script(script)
end
```

**Comment by criticerz** [comment]
Thanks for sharing that @tonymarklove! @wagner for some reason, your solution kept writing the numbers out of order :(

**Comment by eliotsykes** [comment]
In case you need a solution that has no jQuery dependency and works with Capybara field locators:

```rb
  # Usage examples:
  # fill_in_stripe_field 'Credit card', with: '4242424242424242'
  # fill_in_with_force 'CVC', with: 123
  def fill_in_with_force(locator, with:)
    field_id = find_field(locator)[:id]
    page.execute_script "document.getElementById('#{field_id}').value = '#{with}';"
  end

  alias_method :fill_in_stripe_field, :fill_in_with_force
```
Source: https://github.com/eliotsykes/rails-testing-toolbox/blob/master/stripe_helper.rb
