### ISSUE TITLE
autocomplete recommendations

### ISSUE THREAD

**Issue by taf2** [stripe/jquery.payment#154]
for ccv i believe it makes sense in the README.md to recommend using autocomplete="cc-csc" instead of autocomplete="off" because off is not really supported by browsers anymore.  See this nice reference: http://www.html5rocks.com/en/tutorials/forms/requestautocomplete/

**Comment by jamesreggio** [comment]
We recommend `autocomplete="off"` because the best-practices for credit cards (as issued by industry regulators, like the PCI council) discourage storing the CCV/CSC. The idea is that requiring users to manually enter it helps to confirm possession of the physical card.

**Comment by taf2** [comment]
That makes sense but in recent browsers autocomplete=off does not work.

On Friday, April 3, 2015, James Reggio <notifications@github.com> wrote:

> We recommend autocomplete="off" because the best-practices for credit
> cards (as issued by industry regulators, like the PCI council) discourage
> storing the CCV/CSC. The idea is that requiring users to manually enter it
> helps to confirm possession of the physical card.
>
> —
> Reply to this email directly or view it on GitHub
> <https://github.com/stripe/jquery.payment/issues/154#issuecomment-89397962>
> .
>


-- 
*Todd Fisher*
Tel: +1 (410) 394-9424 | Toll Free: +1 (800) 577-1872
todd@calltrackingmetrics.com | calltrackingmetrics.com

**Comment by jamesreggio** [comment]
The [spec](https://html.spec.whatwg.org/multipage/forms.html#autofilling-form-controls:-the-autocomplete-attribute) seems to indicate that `autocomplete="off"` should work, though I'd expect certain third-party tools will ignore it. Could you be specific?

**Comment by taf2** [comment]
@jamesreggio - chrome and I believe safari both ignore autocomplete="off" e.g. blink and webkit.
