### ISSUE TITLE
Card expiry month allows 13-19 entries

### ISSUE THREAD

**Issue by bogdanzurac** [stripe/jquery.payment#156]
The card expiry entry for month not only allows 1-12 values, bot also 13 through 19. 20 and up are restricted. Is this intended or just not accounted for?

**Comment by bogdanzurac** [comment]
No input whatsoever?

**Comment by mduvall** [comment]
Hi @bogdanzurac,

Sorry about the late response here. I have opened a fix for this issue here: https://github.com/stripe/jquery.payment/pull/180.
