### ISSUE TITLE
Maestro definitions need to include the 6220 bin range and support 19 digits

### ISSUE THREAD

**Issue by sudhirj** [stripe/jquery.payment#157]
Maestro cards issued by the State Bank of India are of the form `6220 180 XXXX XXXX XXXX` - currently the library wrongly classifies them as Discover cards and invalidates them because Discover uses 16 digits.

https://www.google.co.in/search?q=maestro+card+number+in+india&espv=2&biw=1430&bih=778&source=lnms&tbm=isch&sa=X&ei=VxUuVbSGNYK0uAT1uoKABw&ved=0CAYQ_AUoAQ&dpr=2#imgrc=1Gtcl8jbbDItFM%253A%3BsWdhHH6rERe-xM%3Bhttp%253A%252F%252F2.bp.blogspot.com%252F-mP8Xwf5v1QI%252FUOEgMRUcB9I%252FAAAAAAAAF0s%252F8YP3C8JUTCU%252Fs640%252Fsbi_debit_card%252B(Small).jpg%3Bhttp%253A%252F%252Fbanking.educationgovt.com%252F2013%252F09%252Fonline-prepaid-recharge-airtel-using.html%3B640%3B400

https://www.google.co.in/search?q=maestro+card+number+in+india&espv=2&biw=1430&bih=778&source=lnms&tbm=isch&sa=X&ei=VxUuVbSGNYK0uAT1uoKABw&ved=0CAYQ_AUoAQ&dpr=2#imgrc=9n9E6ucd_DaovM%253A%3BKXgXNR79NPcVRM%3Bhttp%253A%252F%252F2.bp.blogspot.com%252F-Xm08IrC9UIU%252FT3ledRKB5YI%252FAAAAAAAAAK0%252F2ddQIIUpdLw%252Fs1600%252Fsbi-card-to-card-transfer.jpg%3Bhttp%253A%252F%252Fpankaj-tips.blogspot.com%252F2011%252F04%252Fsbi-atm-card-to-card-money-transfer-atm.html%3B565%3B476

**Comment by mduvall** [comment]
Fixed by https://github.com/stripe/jquery.payment/pull/181
