### ISSUE TITLE
Date format is incompatible with stripe.js

### ISSUE THREAD

**Issue by jordanlev** [stripe/jquery.payment#160]
Your docs for making custom forms link to this plugin, but this plugin assumes the expiration date is a single field, whereas stripe.js requires that expiration date be sent as 2 different fields (month and year). I see a pull request (#38) related to this issue, but it hasn't been merged.

I'd assume that since you're linking here from the official stripe.js documentation that this can actually be used out-of-the-box with stripe.js, but it appears that it can't? (Or perhaps I'm missing something and it is possible?). I'd suggest addressing this in the docs because it is super confusing (at least to me, as a developer who is new to stripe).

**Comment by jordanlev** [comment]
I just found https://github.com/stripe/jquery.payment#paymentcardexpiryvalstring-and-fnpaymentcardexpiryval , which seems to explain how to extract month and year from a single field. So I guess that's how you do it... but would be really nice if the docs and examples mentioned this since it seems like integrating with stripe.js would be the number 1 primary use case.

**Comment by tomfbiz** [comment]
I agree that this is confusing. Do you expect us to not use the payment('formatCardExpiry') when using stripe.js?

Or do you expect us to not use the data-stripe= when using jquery.payment?

Is this an oversight, or just an extra feature that's for non-stripe users?

An example using both of the libraries would be very useful.

**Comment by pdr** [comment]
:+1:  I'm also confused by this! Having stripe.js handle this correctly would be great.

**Comment by LeleDev** [comment]
+1 please fix this one

**Comment by filippolorenzoferraris** [comment]
:+1:

**Comment by LeleDev** [comment]
Still waiting for a fix...

**Comment by raphaelcosta** [comment]
:+1:

**Comment by judetucker** [comment]
:+1:

**Comment by sjelfull** [comment]
@metcalf does you closing this without comment mean you disagree?

**Comment by metcalf** [comment]
@sjelfull much better news than that! It closed automatically when I merged a fix for this problem into Stripe.js. You can now pass an `exp` parameter to `createToken` with a single expiration string. It will handle spaces, dashes, dots and slashes as a separator and handle both year-first and month-first locales. Note that in order to handle both locales, it assumes you'll only pass values with a year after 2012. Otherwise we can't distinguish between "11 / 12" being "Nov 2012" or "Dec 2011". In practice this should be a non-issue since dates before today will error anyway.

**Comment by sjelfull** [comment]
That is supergreat! Thanks for fixing it. Adds to the developer bliss I personally feel working with Stripe!

**Comment by LeleDev** [comment]
Is the validator for this field type still missing?

**Comment by metcalf** [comment]
@LeleDev: You can now pass the single string as the first argument to `validateExpiry`. Sorry for the lack of documentation -- still thinking through the best place to document this additional behavior.

**Comment by NitroBAY** [comment]
Totaly true. Doc says to create 2 field expiration input but scrolling down you see that validation support only 1 field expiration input. I hope you'll fix that, I mean you made a lot of effort to build a good framework but if devs lost many times on such simple stuff it's a waste and doesn't offer a good impression.
Thanks.
