### ISSUE TITLE
Card number formatting doesn't work with invalid numbers

### ISSUE THREAD

**Issue by luongvanphuc** [stripe/jquery.payment#163]
The issue can be reproduced here:
http://stripe.github.io/jquery.payment/example/

Try to input this card number: 1212121212121212
They aren't separated by spaces. My client said, even the number was wrong, it should be separated by spaces.

**Comment by montogeek** [comment]
PR are welcome :)

**Comment by jamesreggio** [comment]
Sorry, formatting invalid cards with an arbitrary schema (e.g., one space every four digits) is not in the scope of this library.
