### ISSUE TITLE
editing the formatted card number places the cursor at the end

### ISSUE THREAD

**Issue by shpandian** [stripe/jquery.payment#165]
Hi,

We are trying to integrate this on our app for the input field "credit card number", everything works fine until we edit - meaning after we enter the complete credit card number and it gets formatted beautifully, but if i want to change any number in between by deleting any digit(apart from last one set) it puts the cursor at the last in stead of the place i want to edit. Could you look into this?

Thanks
Shanmugapriya

**Comment by tomsommer** [comment]
This is fixed in #170

**Comment by shpandian** [comment]
perfect! Thank you!
