### ISSUE TITLE
$.payment.validateCardExpiry(obj.month, obj.year) does not work [expects strings]

### ISSUE THREAD

**Issue by msmyers** [stripe/jquery.payment#178]
Reproduce issue in chrome: 

var obj = $el.payment('cardExpiryVal'); //=> {month: 4, year: 2020}
var val = $.payment.validateCardExpiry(obj.month, obj.year); // FAIL
var val = $.payment.validateCardExpiry(obj); // FAIL
var val = $.payment.validateCardExpiry(''+obj.month, ''+obj.year); // SUCCEED

The reason is:

    $.payment.validateCardExpiry = function(month, year) {
        ...
        month = $.trim(month); // <--- BUG !! A number inputted results in empty string outputted.
        year = $.trim(year);   // <--- BUG !! A number inputted results in empty string outputted.
        ...
    };

To fix:

    $.payment.validateCardExpiry = function(month, year) {
        ...
        month = $.trim(''+month); // <--- BUG !! A number inputted results in empty string outputted.
        year = $.trim(''+year);   // <--- BUG !! A number inputted results in empty string outputted.
        ...
    };

**Comment by jenanwise** [comment]
`validateCardExpiry` is for validating user inputs, hence strings. I agree that the README is not as clear as it could be about input types, but the examples are clear.

`$.trim` also expects string inputs but all versions I've seen auto convert, so .e.g `$.trim(2016)` returns `"2016"`. There are even tests for this behavior in both [jquery](https://github.com/jquery/jquery/blob/fe05cf37ffd4795988f9b2343df2182e108728ca/test/unit/core.js#L227) and [zepto](https://github.com/madrobby/zepto/blob/601372ac4e3f98d502c707bf841589fbc48a3a7d/test/zepto.html#L449).

What version were you using that actually showed this behavior?
