### ISSUE TITLE
Some valid cards prevented from signing up.

### ISSUE THREAD

**Issue by macgregordennis** [stripe/jquery.payment#184]
I've been using this plugin on a recently launched live service. It mostly works well, but I've had numerous complaints from people who weren't able to sign up for our service because the field wouldn't accept the length of their card.

I'm having to disable the upper limit on the form input and the jumping to the next input.

**Comment by jenanwise** [comment]
Do you know the card brand (Visa, Mastercard, etc.), [issuer identification number](https://en.wikipedia.org/wiki/Bank_card_number#Issuer_identification_number_.28IIN.29), and the card length?

**Comment by jenanwise** [comment]
Please re-open or create a new bug if you're able to find that information. Thanks!
