### ISSUE TITLE
.payment('formatCardExpiry'); does not work on iPhone

### ISSUE THREAD

**Issue by birdy247** [stripe/jquery.payment#190]
Hi

I am testing on an iPhone 4 running IOS 7.1.1

.payment('formatCardExpiry'); does not add a "/" into the expiry.  This results in a user entering a expiry as something like "0119" instead of "01/19".  This then causes a validation error.

**Comment by brianlukoff** [comment]
I'm seeing the same issue on the latest version of desktop Safari.

**Comment by birdy247** [comment]
Brian, I just debugged my code and can see that I had a syntax error.  It read

$('input[name=cardExpiry').payment('formatCardExpiry');

I fixed that and it works on the desktop safari.  Untested on iPhone yet!

**Comment by jenanwise** [comment]
Sounds like this was addressed.

**Comment by vkrovi** [comment]
this still seems to be an issue wth iOS
