### ISSUE TITLE
explode mm/yy for data-stripe

### ISSUE THREAD

**Issue by nimasdj** [stripe/jquery.payment#194]
I am using your example form. Please help how can I explode mm/yy of form an assign them to data-stripe="exp-month" and data-strpe="exp-year" respectively to submit it t stripe.js? Please help.

**Comment by jdpedrie** [comment]
Try something like this:

````js
var expirationDate = '10 / 2018';
var matches = expirationDate.match(/([0-9]{2}) \/ ([0-9]{4})/);

Stripe.card.createToken({
      number: cardNumber,
      cvc: cvcCode,
      exp_month: matches[1],
      exp_year: matches[2]
}, stripeResponseHandler);
````

In a real world situation, you'd probably pull `expirationDate`, `number` and `cvcCode` from the form using jQuery.

**Comment by nimasdj** [comment]
@jdpedrie Thanks for trying to help but as about `var expirationDate` what can I use to get it from form assuming I am using the same example form of this repository?

**Comment by nimasdj** [comment]
Beside question above: Instead of regexp match you suggested, how can I use this method to explode and assign them to year and month https://github.com/stripe/jquery.payment#paymentcardexpiryvalstring-and-fnpaymentcardexpiryval ?

**Comment by fstutzman** [comment]
It is unnecessary to explode the MM/YY field into separate elements.  Stripe.js supports passing expiration data as a single field:

https://stripe.com/docs/stripe.js#passing-exp-dates

Hope this helps!

**Comment by nimasdj** [comment]
Thanks.

**Comment by jenanwise** [comment]
Sounds like this was resolved!
