### ISSUE TITLE
formatCard spacing breaks after 4th character

### ISSUE THREAD

**Issue by mattLummus** [stripe/jquery.payment#198]
Using the code:
`$('#subscription_cc_num').payment('formatCardNumber');`

The space in between every 4 characters stops working once you enter more than 4 characters.

I can see it after the 4th...
<img width="273" alt="screen shot 2016-01-11 at 11 09 38 am" src="https://cloud.githubusercontent.com/assets/6342564/12240622/2ab23a0e-b854-11e5-90cf-f46249228574.png">

But once I type in a 5th it reverts.
<img width="271" alt="screen shot 2016-01-11 at 11 09 43 am" src="https://cloud.githubusercontent.com/assets/6342564/12240623/2c80a74e-b854-11e5-950b-c87af36041b6.png">

Have tested this in Chrome, Firefox, and Safari. Running on Macbook Pro, Yosemite.
Have also tested this in a demo I found online with same results. http://jsfiddle.net/gosseti/jv8j53nb/9/

**Comment by jenanwise** [comment]
Hi @mattLummus. The spacing between each group depends on the card type. If you enter `42424`, you'll see the grouping remain. `12345` isn't a known prefix so it reverts to ungrouped.

**Comment by mattLummus** [comment]
@jenanwise That makes sense however I did not see this in the documentation. Thanks for the quick response!
