### ISSUE TITLE
Consider creating a library of validation rules compatible with jqueryvalidation

### ISSUE THREAD

**Issue by alexweissman** [stripe/jquery.payment#201]
[jqueryvalidation](http://jqueryvalidation.org/) is *the* original form validation library for jQuery - in fact, it was created by one of the members of the official jQuery team back when jQuery was first being developed.

It is widely used, and is [fully extendable](http://jqueryvalidation.org/jQuery.validator.addMethod/).  Stripe should consider implementing their credit card validation methods as an extension to jQueryvalidation.  This would make it easy to validate forms that contain credit card fields **and** other fields with a single validation engine.

**Comment by jenanwise** [comment]
Hi there! Please use issues for identifying bugs. We're not planning on building new jquery-based validation libraries, but I'm sure if you built it, someone would use it!
