### ISSUE TITLE
I created a plugin for validating an entire set of payment fields

### ISSUE THREAD

**Issue by alexweissman** [stripe/jquery.payment#202]
I figured a lot of people want an easy way to validate all of their payment fields at once, so I made a plugin:

http://codepen.io/alexweissman/pen/KVbZzQ

Use:
```
// Initialize the payment form plugin
$('#payment-stripe').paymentForm();

// Validate when I click a button
$('#validate').on('click', function(){
  if ($('#payment-stripe').paymentForm('valid'))
    alert('CC info is good!');
  else
    alert('Badman Cardfaker');
});
```

**Comment by jenanwise** [comment]
Hi there! Please use issues for identifying bugs. Thanks!

**Comment by alexweissman** [comment]
Umm, alright, you're welcome.  Have you considered enabling a wiki for user-generated content, then?
