### ISSUE TITLE
Spaces aren't inserted correctly when formatting a card number input

### ISSUE THREAD

**Issue by courthead** [stripe/jquery.payment#203]
STR:

- Go to the [demo](http://stripe.github.io/jquery.payment/example/).
- In the card number field, type `12345`.
- **Expected:** The input now reads `1234 5`.
- **Actual:** The input now reads `12345`.

I think this commit is the culprit: https://github.com/stripe/jquery.payment/commit/3dc241e9188407042026c6d39ee74480504c3715

After this commit, all non-digits are stripped from the number inserted after each keystroke.

**Comment by jenanwise** [comment]
`12345` doesn't match any known credit card formats, so `jquery.payment` doesn't know how to format it. Try `4242 4242 4242 4242` for a valid fake Visa, for example. You can see some additional fake cards here: https://stripe.com/docs/testing

**Comment by courthead** [comment]
Ah, I was thinking that even if the user makes a mistake (resulting in the number being invalid), it'd be nice to still format the numbers in some common way (e.g. `1234 5678 9012 3456`).

**Comment by dcarral** [comment]
Actually, @courthead suggestion (4-digit groups instead of ungrouped by default) makes sense. It would be great if this behavior could be configurable. 

@jenanwise: Would you guys be interested in adding something in that line?
