### ISSUE TITLE
$.payment.cards example is outdated

### ISSUE THREAD

**Issue by Nirazul** [stripe/jquery.payment#205]
We've experienced an error when updating to `1.3.2` (from `1.3.0`), because `$.payment` expects additional card definitions to contain a `patterns` array instead of a `pattern` regex, as your example states:
https://github.com/stripe/jquery.payment/tree/gh-pages#paymentcards

I'd do a pull-request myself but unfortunately I'm unsure what sort of example would fit this change.

To me, this seems to be an important change, that'll break quite some code out there. So this change should be more than just patch release and should also be written in the release notes. 
We had to update to take care of a bug on android devices (CVC year split) and strange behaviours on mobile when deleting a number (Flash of å).

**Comment by domi55** [comment]
How about an UATP example?

```
{
  type: 'uatp',
  patterns: [1],
  format: /(\d{1,4})(\d{1,5})?(\d{1,6})?/,
  length: [15],
  cvcLength: [0],
  luhn: true
 }
```
https://en.wikipedia.org/wiki/Bank_card_number

**Comment by jenanwise** [comment]
Hi @Nirazul! You're absolutely right that this should have been a breaking change. Apologies for that. I'll fix the README.
