### ISSUE TITLE
Icons don't appear on iOS 9.3 safari 

### ISSUE THREAD

**Issue by scottcarlton** [stripe/jquery.payment#207]
When inputing a credit card on mobile Safari the icon doesn't appear.
In the Xcode immolator it works but on an actual device is doesn't. It will appear if you start to backspace.

Has anyone else ran into this?

**Comment by jenanwise** [comment]
Hi @scottcarlton. Icons for what? `jquery.payment` doesn't ship with any icons. Can you please link to a jsfiddle reproducing your issue?
