### ISSUE TITLE
No releases for recent fixes?

### ISSUE THREAD

**Issue by karlatkinson** [stripe/jquery.payment#209]
We're using this package for payment card validation and formatting.
There have been several pull requests merged onto the master branch but no releases to github or pushes to npm.

The project looks active but is there a reason for the lack of releases?

**Comment by jenanwise** [comment]
No particular reason! We'll bundle up a release soon. Sorry for the delay!

**Comment by jenanwise** [comment]
I just cut 1.3.3. Hope that works for you!
