### ISSUE TITLE
Don't rely on window.$

### ISSUE THREAD

**Issue by jbrooksuk** [stripe/jquery.payment#210]
`window.$` is not always available, especially if you're building your application with Browserify or something and using `var $ = require('jquery')`.

**Comment by jenanwise** [comment]
This library requires jQuery, and tests for `window.jQuery or window.Zepto or window.$`.

**Comment by jbrooksuk** [comment]
If you're using Browserify this doesn't work though, but you can mimic it by doing:

```js
var $ = require('jquery');
window.jQuery = $;
```
