### ISSUE TITLE
Too slow on mobile devices

### ISSUE THREAD

**Issue by aanders77** [stripe/jquery.payment#211]
In my experience, the $.payment.fn.formatCardNumber function is too slow for mobile devices. When the user knows his card number by heart and taps the digits fast, the mobile device isn't able to keep up and omits some digits. The function should be optimized in some way to be more efficient.

At least this is true for my Samsung Galaxy S4 using Chrome for Android. (I'm sure that my phone isn't the slowest one on the market, even if it is a few years old.)

**Comment by jenanwise** [comment]
Hi there @aanders77! If you've profiled a specific bottleneck and have a specific recommendation, we're all ears, but it's not otherwise a high priority for us.
