### ISSUE TITLE
Update Elo IINs

### ISSUE THREAD

**Issue by dcarral** [stripe/jquery.payment#221]
## Expected behavior

Library supports an up-to-date range of [IINs](https://en.wikipedia.org/wiki/Bank_card_number#Issuer_identification_number_.28IIN.29) (formerly known as BINs) for Elo.

After asking the Brazilian payment provider [allpago](http://www.allpago.com/) for Elo's IINs, I got the following list back (via e-mail, no public link available):

> 401178	636368
> 401179	650031 to 650033
> 431274	650035 to 650051
> 438935	650405 to 650439
> 451416	650485 to 650538
> 457393	650541 to 650598
> 457631	650700 to 650718
> 457632	650720 to 650727
> 504175	650901 to 650920
> 506699 to 506778	651652 to 651679
> 509000 to 509999	655000 to 655019
> 627780	655021 to 655058
> 636297

## Actual behavior

Library supports a subset of the actual range.

## Steps to reproduce

Enter a Elo credit card number belonging to the not-yet-supported ranges. It will be detected as either invalid or as another credit card type

**Comment by jenanwise** [comment]
Fixed with #222 / #223.
