### ISSUE TITLE
Some combinations of card number do not formated well

### ISSUE THREAD

**Issue by webhive** [stripe/jquery.payment#231]
On your demo page trying to type card number

## Expected behavior

When typing card number expecting to see spaces after each 4 digits

## Actual behavior

Typing ``1111`` - everything ok and space added after 4-th digit.  But typing next digits this space disappears and final number typed without spaces.

If typing 444444444, 22222222222, 55555555555, 88888888 - spaces added well
If typing 111111111, 333333333333, 666666666 - there are no spaces

Suspect spaces not added when card type is not detected.  

Chromium  51.0.2704.84 (64-bit) (Linux)

## Steps to reproduce

Just start typing in number field

**Comment by jenanwise** [comment]
Hi @webhive. jquery.payment only knows how to format known BINs/IINs. `1111` etc do not match any actual cards.
