### ISSUE TITLE
Elo Card type not valid

### ISSUE THREAD

**Issue by amanuni** [stripe/jquery.payment#235]
We are using this library.

When someone enter their card number starting with 4514 is recognize as elo card type but customer told us that its visa card type.

We have added method for auto reorganization of card type for making payment but for above card type not working properly if would be great if you guys help me.

**Comment by jtnotat** [comment]
Also having this issue, customer's Visa (4514) being misidentified as Elo.

**Comment by amanuni** [comment]
This problem is happens with me also guys please look into that and rectify it.
