### ISSUE TITLE
How to validate Debit Cards

### ISSUE THREAD

**Issue by usamamashkoor** [stripe/jquery.payment#237]
is their is any way we can validate debit cards using jquery.payment

Fields are 
Routing & Account Number

Thanks and Regards
M.Usama

**Comment by jenanwise** [comment]
jquery.payment works with anything that looks like a credit card. Debit cards use a card number, just like credit cards, so that will work. Routing and account number (for bank transfers) are not part of this library.

**Comment by usamamashkoor** [comment]
Thanks
