### ISSUE TITLE
Request: Raw Card Value

### ISSUE THREAD

**Issue by oscarmorrison** [stripe/jquery.payment#238]
## Expected behavior

$('input.cc-number').payment('cardValue') //=> {cardNumber: 4111111111111111, cardType: 'visa'}

## Actual behavior

Functionality does not exist.

## Notes

Consider there is some excellent functionality to format cards, it would be excellent to be able to easily pull the raw card number using this library. (this is obviously easy enough todo with a string replace or something), but that makes some assumptions about the formatting.

**Comment by jenanwise** [comment]
Hi there. Thanks for writing, but we are not accepting new feature requests at this time. Please see the README, the contributing guidelines, and the issue template for details. Thank you!
