### ISSUE TITLE
Can't make 19 digits length custom card

### ISSUE THREAD

**Issue by SerikK** [stripe/jquery.payment#239]
I have such [code](https://jsfiddle.net/qqztoxej/) and I want to make the possibility to enter 19 digits instead of 16. How I can do that?

**Comment by jenanwise** [comment]
Hi there @SerikK. You can use custom cards with 19 digits. Your pattern is being masked by another pattern (they are selected in order). You want to use more-specific patterns and use `unshift` rather than `push`.

**Comment by SerikK** [comment]
Thanks @jenanwise , Worked like a charm.
