### ISSUE TITLE
Execute formatting

### ISSUE THREAD

**Issue by Fogush** [stripe/jquery.payment#242]
Hello,
Is there a way to format a credit card field by executing something?
For example, a credit card form has errors on the back-end side (payment service did not accept a card), an application generates the form with previously entered data. At that moment, the credit card number field has a value like "4012000033330026" (without formatting), but when I execute cardNumber.payment('formatCardNumber') it does nothing, i.e. the value doesn't have spaces in proper positions. It will format the field only when a user changes the value.
So the issue is to format fields with existing values.
It can be solved by something like cardNumber.payment('formatCardNumber').change(), but maybe is there a more elegant way?
Thanks

**Comment by jenanwise** [comment]
@Fogush Triggering a `change()` is your best bet.
