### ISSUE TITLE
Some Visas Wrongly Categorized As Visa Electron

### ISSUE THREAD

**Issue by willisplummer** [stripe/jquery.payment#243]
Hey!

The following Visa cards are wrongly categorized as Electron:

- Lloyds TSB VISA (BIN: 450823)
- Co-operative Bank Visa Debit Card (formerly Visa Electron) (BIN: 450875)
- Banco de Chile Visa Credit Card (BIN: 450878)

[source](http://www.liquisearch.com/list_of_issuer_identification_numbers/bin_ranges/banking_and_financial_4*****/visa_45****)

Can we get a little more specific with the Visa Electron range so that users with Visa cards from these banks are able to make payments?

Thanks so much!

![bitmoji](https://render.bitstrips.com/v2/cpanel/9021226-166716282_1-s1-v1.png?transparent=1&width=246)

**Comment by jenanwise** [comment]
Hi @willisplummer. Thanks for filing! You're right that these were false positives. I think rather than adding more strict Visa Electron ranges, we're just going to remove Visa Electron entirely. See #244 for details.

**Comment by jenanwise** [comment]
I've released 2.0.0 which solves this, as per #244.
