### ISSUE TITLE
Stripe Checkout

### ISSUE THREAD

**Issue by virtapoika** [stripe/jquery.payment#245]
Hi!

I couldn't find any better place to send this.. I'm using the html form of stripe checkout. It appears to open correctly on Android (through cordova and web browser) but on iOS trought cordova it only dims the screen for a while and if using safari it opens  checkout window on seperate tab.

Thanks for the help!

**Comment by guillaumehenriot** [comment]
Hi @virtapoika,

This space is used for bugs reports about jquery.payments, a library helping the implementation of payment forms. If you want an answer about a specific Checkout integration question you should send an email to our support:
https://support.stripe.com/email

I'll close this issue for now.

**Comment by virtapoika** [comment]
Thanks!
