### ISSUE TITLE
MS Edge Mobile: Expiry input problems

### ISSUE THREAD

**Issue by nilssolanki** [stripe/jquery.payment#247]
## Expected behavior

When typing the numbers into the expiry field, the input should work as expected. One tap on a number equals one number in the input field.

## Actual behavior

The `1` key always end up entering `11 /` instead of `1 /`. The other numerical keys seem to input numbers twice as well, although not as consistently as the `1` key (e.g. `04 / 4` if the `4` key was hit).

Device and Browser:
Microsoft Lumia 550, Microsoft Edge 25.10586.420.0

## Steps to reproduce

Using a Lumia 550 (or a similar device), go to http://stripe.github.io/jquery.payment/example/ and try tapping the `1` key when in the expiry field.

**Comment by jenanwise** [comment]
Hi @nilssolanki! Can you help track down what's happening for us? Unfortunately, I don't have a MS Edge Mobile device handy, and I can't reproduce on desktop.

**Comment by nilssolanki** [comment]
Hi Jenan, thank you for the quick response. Yes, I can try, although I don't have a windows machine at hand, so my debugging capabilities will be limited. Unfortunately, this bug doesn't show up in the desktop simulator, we had to buy a device to reproduce it :)

Do you have any good ideas on how to debug in a situation like this?

**Comment by jenanwise** [comment]
You can try "printing" to the document. Something like this:

```js
// create a are on the page to write text
var printArea = document.createElement('div');
document.body.appendChild(printArea);

// later in some part of the code that you would normally `console.log`
var text = document.createElement('p');
text.textContent = ' foo bar'
printArea.appendChild(text);
```

I should note that if this is really only happening on Lumia 550s (or MS Edge mobile in general), we may not be able to fix it. The event system / input handling is fairly complex and fragile (hence the notes at the top of the README), and MS Edge mobile traffic is likely a very small percentage of live traffic.

**Comment by jenanwise** [comment]
Hi @nilssolanki. I'm going to close as not-reproducible due to lack of activity. Please re-open with more info if you have further information!
