### ISSUE TITLE
validateCardExpiry always returns false

### ISSUE THREAD

**Issue by mikemand** [stripe/jquery.payment#253]
## Expected behavior

`$.payment.validateCardExpiry(expiry);` should return true if a valid month and year (for example `10/20`) are passed in the `expiry` object.

## Actual behavior

Using `var expiry = $('input.card-expiry').payment('cardExpiryVal');` to get the expiration value, `$.payment.validateCardExpiry()` always returns false no matter what format I pass the month and year. Likewise, any month and year combination I have tried fails. Here are some that I've tried:

```js
$.payment.validateCardExpiry(expiry);
$.payment.validateCardExpiry(expiry.month, expiry.year);
$.payment.validateCardExpiry(expiry.month + '', expiry.year + '');
$.payment.validateCardExpiry("'" + expiry.month + "'", "'" + expiry.year + "'");
$.payment.validateCardExpiry(new String(expiry.month), new String(expiry.year));
```

I have tested on Chrome Version 53.0.2785.143 (64-bit) on OS X 10.11.6 so far.

## Steps to reproduce

An example of the problem can be found here: http://jsfiddle.net/gosseti/x9vhpeL7/ (from the article here: http://gosseti.com/demos/a-better-card-payment-form). The `Expires` field should be outlined in green when putting in any valid expiration date, but it isn't.

**Comment by shaunstripe** [comment]
Unable to reproduce.

I'm on Chome Version 54.0.2840.71 (64-bit) on OS X 10.11.6.  This is what I see when inputting your example expiry in the jsfiddle:

<img width="427" alt="screen shot 2016-10-25 at 11 58 08 am" src="https://cloud.githubusercontent.com/assets/17118312/19695835/573e9390-9aaa-11e6-8986-fe67871b13d2.png">

**Comment by duanewilson** [comment]
FYI - Seems to also work fine in Safari Version 10.0.1 (12602.2.14.0.7) Mac OS X 10.12.1

![screen shot 2016-10-25 at 10 04 23 am](https://cloud.githubusercontent.com/assets/1859378/19696108/b3ef82e4-9a9a-11e6-968b-061c4f3e0495.png)

**Comment by mikemand** [comment]
How odd. It appears to be working now. Thank you for working the voodoo and correcting the problem. 😄
