### ISSUE TITLE
we can input the English character in your demo on IE. But in fact i think it should limit that users can just only input numbers

### ISSUE THREAD

**Issue by kobe990** [stripe/jquery.payment#254]
## Expected behavior

In your demo, it should be that users can only input the number in the credit card text input on all browsers.

## Actual behavior

we can input the English character on the IE in your demo (ALL IE browsers)

## Steps to reproduce

* open the demo in your repository. 
* and input the English characters in the credit card input on any IE browser. 
* then you will find the bug.

**Comment by shaun-stripe** [comment]
Thanks for reporting, but we're only fixing critical bugs right now for this project.
