### ISSUE TITLE
'4222 2222 2222 2' is "valid"

### ISSUE THREAD

**Issue by oaleynik** [stripe/jquery.payment#255]
## Expected behavior

Should be false (right?)

## Actual behavior

`$.payment.validateCardNumber('4222 2222 2222 2') // => true`

**Comment by shaun-stripe** [comment]
Thanks for reporting.  I'm not sure what's causing this-- any fewer or more digits will cause the valid check to fail.  We can only handle critical bugs right now for this project, so we have to close.

**Comment by jenan-stripe** [comment]
It's correct behavior. Visas can be from 13 to 16 digits long: https://github.com/stripe/jquery.payment/blob/f0e303b3769e9bbbc22ca2eb4a3e97f64745ab33/src/jquery.payment.coffee#L43
