### ISSUE TITLE
Please allow CVC be longer then 4 digits

### ISSUE THREAD

**Issue by Paxa** [stripe/jquery.payment#256]
In current implementation it's strictly `<= 4`

```js

  restrictCVC = function(e) {
    var $target, digit, val;
    $target = $(e.currentTarget);
    digit = String.fromCharCode(e.which);
    if (!/^\d+$/.test(digit)) {
      return;
    }
    if (hasTextSelected($target)) {
      return;
    }
    val = $target.val() + digit;
    return val.length <= 4;
  };
```

But some banks have private label cards, that can have longer cvv number

**Comment by Paxa** [comment]
Also would be nice to have access to `cardFromNumber, cardFromType, cards, defaultFormat, formatBackCardNumber, formatBackExpiry, formatCardNumber, formatExpiry, formatForwardExpiry, formatForwardSlashAndSpace, hasTextSelected, luhnCheck, reFormatCVC, reFormatCardNumber, reFormatExpiry, reFormatNumeric, replaceFullWidthChars, restrictCVC, restrictCardNumber, restrictExpiry, restrictNumeric, safeVal, setCardType` from outside.

I never understand what is benefited to make plugin not customizable by making variable hidden

**Comment by jenan-stripe** [comment]
Hi there -- sorry, but we're not adding new features at this time. Please see the project status in the readme.

**Comment by Paxa** [comment]
Ok, thank you for fast response!
