### ISSUE TITLE
Card number formatting breaking with copy and paste.

### ISSUE THREAD

**Issue by ellisio** [stripe/jquery.payment#260]
## Expected behavior

When you copy and paste a card number into a `formatCardNumber`-applied element, then entering a CVC into a `formatCardCVC`-applied element, the card number should retain it's formatting.

## Actual behavior

The formatting on the card number is lost upon entering your CVC number. To get the formatting back the user has to tab back to the card number field and delete a single number.

Chrome Version 55.0.2883.95 (64-bit)
jquery.payment v3.0.0

## Steps to reproduce

http://d.pr/v/FLlA -- Video displaying the behavior.

**Comment by jenan-stripe** [comment]
There shouldn't be any interaction between the cvc and card fields. It looks like this might be an integration issue. If it's still a problem, can you please re-open with a minimal jsfiddle or equivalent?
