### ISSUE TITLE
Mastercard 2 BIN series acceptance

### ISSUE THREAD

**Issue by justqyx** [stripe/jquery.payment#270]
> Mastercard is providing live/production non-reloadable prepaid cards to customers to help them validate acquirer/processor and merchant readiness for the new 2 series Mastercard bank identification number (BIN) range (222100–272099). These cards are being offered to customers as an optional turnkey solution intended for testing in production environments.

**Comment by jenan-stripe** [comment]
Hi @justqyx -- jquery.payment already supports this: https://github.com/stripe/jquery.payment/blob/f0e303b3769e9bbbc22ca2eb4a3e97f64745ab33/src/jquery.payment.coffee#L49-L52

**Comment by justqyx** [comment]
Thanks.
