### ISSUE TITLE
Expierd date can be 00/00

### ISSUE THREAD

**Issue by ledevinchi** [stripe/jquery.payment#274]
I'm using jquery.payment in my project, perfect js, but I found a bug. when I enter 00 / 00 it's correct and the google chrome is giving error: Uncaught RangeError: Maximum call stack size exceeded

**Comment by jenan-stripe** [comment]
Hello! This repository is deprecated. Please see the readme. I was also unable to reproduce the error here: http://stripe.github.io/jquery.payment/example/
