### ISSUE TITLE
I published jquery.payment to npm

### ISSUE THREAD

**Issue by elliotf** [stripe/jquery.payment#44]
Hello nice people,

I find it useful to have modules published to npm to allow for easier version tracking, so I published jquery.payment to npm.

However, I am not the author.  I've added maccman as an author, so hopefully that's good enough.

Please let me know if I've done a bad bad thing or if you'd like anything else.

Thank you!

**Comment by slorber** [comment]
@maccman 


> We’ve written a general purpose library called jQuery.payment to help with client-side input validation and formatting card numbers.

https://stripe.com/docs/custom-form


I don't really understand. Is this lib for server or client side use?

Also as of 2016 someone may want to use this lib with CommonJS / Browserify / Webpack iinstead of a jquery plugin

**Comment by jenanwise** [comment]
@slorber jQuery.payment is for frontend development, and it is [currently available in NPM](https://www.npmjs.com/package/jquery.payment).
