### ISSUE TITLE
TypeError: 'undefined' is not an object (evaluating '$.payment.fn[method].apply')

### ISSUE THREAD

**Issue by ambasador** [stripe/jquery.payment#70]
Any body know how to remove this error

TypeError: 'undefined' is not an object (evaluating '$.payment.fn[method].apply')

**Comment by chrisdrackett** [comment]
so I'm running into this too. I have the following input:

> <input class="expire-date" id="id_expire_date" maxlength="7" placeholder="Expiration Date (MM/YY)" type="tel">

and then my js includes:

> $('#id_expire_date').payment('formatCardExpiry');

So far everything works as expected. The field formats correctly, etc. Next I try and setup submitting the form. I have the following within an empty form.submit:

> $('#id_expire_date').payment('cardExpirtVal')

when I submit the form (regardless of the value in this field) I get the error referenced above. I'm going to attempt further debugging.

**Comment by patrickgordon** [comment]
@chrisdrackett you got a typo:
`$('#id_expire_date').payment('cardExpirtVal')` 

to

`$('#id_expire_date').payment('cardExpiryVal')`

**Comment by chrisdrackett** [comment]
Time to stop coding for the day! Thanks :)
